<a href="https://colab.research.google.com/github/xinxingwu-uk/Experiments_C_S/blob/main/AssociationAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import libraries
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

In [2]:
loadData=[['Shirt','Trousers','Ties'],
          ['Trousers'],
          ['Shirt','Ties'],
          ['Shirt','Ties'],
          ['Shirt','Trousers']]

In [3]:
loadData

[['Shirt', 'Trousers', 'Ties'],
 ['Trousers'],
 ['Shirt', 'Ties'],
 ['Shirt', 'Ties'],
 ['Shirt', 'Trousers']]

---
# Apriori Algorithm and One-Hot Encoding

#### Apriori's algorithm transforms True/False or 1/0.

#### Using TransactionEncoder, we convert the list to a One-Hot Encoded Boolean list.

#### Products that customers bought or did not buy during shopping will now be represented by values 1 and 0.
---

In [4]:
#Let's transform the list, with one-hot encoding
te = TransactionEncoder()
te_data = te.fit(loadData).transform(loadData)
#te_data =te.fit_transform(loadData)
te_df = pd.DataFrame(te_data,columns=te.columns_)
te_df_rp0 = te_df.replace(False,0)
te_df_rp01 = te_df_rp0.replace(True,1)
te_df_rp01

   Shirt  Ties  Trousers
0      1     1         1
1      0     0         1
2      1     1         0
3      1     1         0
4      1     0         1

---
# Applying Apriori and Resulting

#### The next step is to create the Apriori Model. We can change all the parameters in the Apriori Model in the mlxtend package.

#### Use minimum support parameters for this modeling.

#### For this, I set a min_support value with a threshold value of 60% and printed them on the screen as well.
---

In [5]:
# Find frequent item sets
#set a threshold value for the support value and calculate the support value.
frequent_items = apriori(te_df_rp01, min_support = 0.6, use_colnames = True)
frequent_items

   support       itemsets
0      0.8        (Shirt)
1      0.6         (Ties)
2      0.6     (Trousers)
3      0.6  (Shirt, Ties)

---
#### Chose the 80% minimum confidence value. In other words, when product X is purchased, we can say that the purchase of product Y is 80% or more.
---

In [6]:
# Generate strong association rules
#Let's view our interpretation values using the Associan rule function
rules = association_rules(frequent_items, metric = "confidence", min_threshold = 0.8)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Ties),(Shirt),0.6,0.8,0.6,1.0,1.25,0.12,inf

In [7]:
rules_sorted = rules.sort_values(by='confidence', ascending =False)
rules_sorted

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Ties),(Shirt),0.6,0.8,0.6,1.0,1.25,0.12,inf